// pvp.js — the live Dojo duel itself, once two students are matched (see dojo.js). Reuses
// the exact same battle overlay/HP bars/round types as monster battles (battle.js), but is
// driven by Firebase instead of local monster AI: both students see the identical
// question each round (one shared pile, generated by whichever side currently needs to
// start a round), answer blind, and only see the outcome once both have submitted.
//
// Sync design, in one sentence: every field in pvpBattles/{code} has exactly one writer
// (each side writes only its own hp/name/gold/answer; only the HOST ever writes round
// progression), so two browsers can never race to overwrite the same key.

const PVP_ROUND_TIMEOUT_MS = 45000; // time to answer before it's an automatic miss
const PVP_STALL_GRACE_MS = 20000;   // extra wait after that before assuming the opponent's gone
const PVP_GOLD_BONUS_PCT = 0.10;

let pvpCode = null;
let pvpRole = null; // 'host' | 'guest'
let pvpUnwatch = null;
let pvpEnded = false;
let pvpAnsweredThisRound = false;
let pvpCurrentRound = 0;
let pvpResolvedRound = 0;
let pvpRoundTimeoutHandle = null;
let pvpStallHandle = null;

function pvpMyKey() { return pvpRole; }
function pvpOppKey() { return pvpRole === 'host' ? 'guest' : 'host'; }

function pvpStopWatching() {
  if (pvpUnwatch) { pvpUnwatch(); pvpUnwatch = null; }
}
function pvpClearTimers() {
  if (pvpRoundTimeoutHandle) { clearTimeout(pvpRoundTimeoutHandle); pvpRoundTimeoutHandle = null; }
  if (pvpStallHandle) { clearTimeout(pvpStallHandle); pvpStallHandle = null; }
}

function pvpOpponentAvatarDataUri(name) {
  const initial = ((name || '?').trim().charAt(0) || '?').toUpperCase();
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120">`
    + `<circle cx="60" cy="60" r="56" fill="#39a08c" stroke="#0f1c22" stroke-width="4"/>`
    + `<text x="60" y="78" font-family="monospace" font-size="56" font-weight="700" fill="#07171a" text-anchor="middle">${initial}</text></svg>`;
  return 'data:image/svg+xml;base64,' + btoa(svg);
}

function updatePvpHpBars(myHp, myMaxHp, oppHp, oppMaxHp) {
  const myPct = Math.max(0, Math.round((myHp / myMaxHp) * 100));
  const oppPct = Math.max(0, Math.round((oppHp / oppMaxHp) * 100));
  battlePlayerHpFill.style.width = myPct + '%';
  battlePlayerHpFill.classList.toggle('low', myPct <= 40);
  battleMonsterHpFill.style.width = oppPct + '%';
  battleMonsterHpFill.classList.toggle('low', oppPct <= 40);
}

async function startPvpDuel(code, role) {
  pvpCode = code;
  pvpRole = role;
  pvpEnded = false;
  pvpAnsweredThisRound = false;
  pvpCurrentRound = 0;
  pvpResolvedRound = 0;

  scene.modalOpen = true;
  battleOverlay.classList.remove('hidden');
  battleModeTag.textContent = '';
  battleMonsterSprite.src = '';
  drawBattlePlayerSprite();
  battleBody.innerHTML = '';
  battleBody.appendChild(statusHeading('Connecting\u2026'));

  currentBattleFinish = () => pvpForfeit();

  await Shared.reportBattleReady(code, role, playerStats.hp, playerStats.maxHp, session.name, session.record.coins || 0);
  pvpUnwatch = Shared.watchBattle(code, onPvpBattleChange);
}

function onPvpBattleChange(data) {
  if (pvpEnded) return;
  if (!data) { pvpEndAborted(); return; }

  const oppName = data[pvpOppKey() + 'Name'];
  if (oppName) {
    battleMonsterName.textContent = oppName;
    battleMonsterSprite.src = pvpOpponentAvatarDataUri(oppName);
  }
  const myHp = data[pvpMyKey() + 'Hp'], myMaxHp = data[pvpMyKey() + 'MaxHp'];
  const oppHp = data[pvpOppKey() + 'Hp'], oppMaxHp = data[pvpOppKey() + 'MaxHp'];
  if (typeof myHp === 'number' && typeof oppHp === 'number') {
    updatePvpHpBars(myHp, myMaxHp, oppHp, oppMaxHp);
  }

  if (data.status === 'over') { handlePvpOver(data); return; }

  const bothReady = typeof data.hostHp === 'number' && typeof data.guestHp === 'number';
  if (bothReady && !data.status && pvpRole === 'host') {
    const roundKey = pickRoundKey();
    const pile = generatePVDigits();
    Shared.startBattleRound(pvpCode, 1, { moduleKey: roundKey, active: pile.active, digits: pile.digits });
    return;
  }

  if (data.status === 'question') {
    if (data.round !== pvpCurrentRound) {
      pvpCurrentRound = data.round;
      pvpAnsweredThisRound = false;
      renderPvpQuestion(data);
      startPvpRoundTimers(data.roundStartedAt);
    }
    if (pvpRole === 'host' && data.hostAnswer && data.guestAnswer && data.round !== pvpResolvedRound) {
      pvpResolvedRound = data.round;
      resolvePvpRound(data);
    }
  }
}

function renderPvpQuestion(data) {
  pvpClearTimers();
  battleModeTag.textContent = QUESTION_MODULES[data.question.moduleKey].name.replace('Place Value \u2014 ', '');
  battleBody.innerHTML = '';
  const qHost = document.createElement('div');
  battleBody.appendChild(qHost);
  QUESTION_MODULES[data.question.moduleKey].render(qHost, {
    presetPile: { active: data.question.active, digits: data.question.digits },
    onCorrect: () => pvpSubmit(true),
    onWrong: () => pvpSubmit(false),
  });
}

function pvpSubmit(correct) {
  if (pvpAnsweredThisRound || pvpEnded) return;
  pvpAnsweredThisRound = true;
  pvpClearTimers();
  // Render the "waiting" screen BEFORE firing the write, not after — submitBattleAnswer()
  // is async, and if the opponent's answer is already in, this submission can trigger
  // resolution (and a Victory/Defeat render) before this function's own code resumes.
  // Rendering first means any later resolution simply overwrites this screen normally,
  // instead of this screen overwriting the resolution.
  battleBody.innerHTML = '';
  battleBody.appendChild(statusHeading('Answer locked in!'));
  const msg = document.createElement('div');
  msg.className = 'wb-modal-body';
  msg.textContent = 'Waiting for your opponent to finish\u2026';
  battleBody.appendChild(msg);
  Shared.submitBattleAnswer(pvpCode, pvpRole, correct);
}

function startPvpRoundTimers(roundStartedAt) {
  const startedMs = typeof roundStartedAt === 'number' ? roundStartedAt : Date.now();
  const remaining = Math.max(0, PVP_ROUND_TIMEOUT_MS - (Date.now() - startedMs));
  pvpRoundTimeoutHandle = setTimeout(() => {
    if (!pvpAnsweredThisRound) pvpSubmit(false); // ran out of time — counts as a miss
  }, remaining);
  pvpStallHandle = setTimeout(() => {
    // Still stuck on this same round well after our own timeout fired, and we already did
    // our part — the opponent's browser is almost certainly gone. Don't leave the match
    // hanging forever.
    if (pvpAnsweredThisRound && !pvpEnded) pvpDeclareOpponentGone();
  }, remaining + PVP_STALL_GRACE_MS);
}

// Host-only: called once both this round's answers are in. Applies the hit, then either
// starts the next round or ends the match — all in a single write, so watchers never see
// an inconsistent halfway state.
function resolvePvpRound(data) {
  const winnerSide = Shared.resolveRoundOutcome(data.hostAnswer, data.guestAnswer);
  let newHostHp = data.hostHp, newGuestHp = data.guestHp;
  if (winnerSide === 'host') newGuestHp = Math.max(0, data.guestHp - 1);
  else if (winnerSide === 'guest') newHostHp = Math.max(0, data.hostHp - 1);

  if (newHostHp <= 0 || newGuestHp <= 0) {
    Shared.applyBattleResolution(pvpCode, {
      hostHp: newHostHp, guestHp: newGuestHp,
      status: 'over', winner: newHostHp <= 0 ? 'guest' : 'host', endedReason: 'ko',
    });
  } else {
    const roundKey = pickRoundKey();
    const pile = generatePVDigits();
    Shared.applyBattleResolution(pvpCode, {
      hostHp: newHostHp, guestHp: newGuestHp,
      status: 'question', round: (data.round || 1) + 1,
      question: { moduleKey: roundKey, active: pile.active, digits: pile.digits },
      hostAnswer: null, guestAnswer: null,
      roundStartedAt: (typeof firebase !== 'undefined' && firebase.database && firebase.database.ServerValue)
        ? firebase.database.ServerValue.TIMESTAMP : Date.now(),
    });
  }
}

function pvpDeclareOpponentGone() {
  if (pvpEnded) return;
  pvpClearTimers();
  Shared.applyBattleResolution(pvpCode, { status: 'over', winner: pvpRole, endedReason: 'opponent_gone' });
}

function pvpForfeit() {
  if (pvpEnded) return;
  pvpClearTimers();
  Shared.applyBattleResolution(pvpCode, { status: 'over', winner: pvpOppKey(), endedReason: 'forfeit' });
}

function handlePvpOver(data) {
  if (pvpEnded) return;
  pvpEnded = true;
  pvpClearTimers();
  pvpStopWatching();
  currentBattleFinish = null;

  const iWon = data.winner === pvpRole;
  const myFinalHp = data[pvpMyKey() + 'Hp'];
  const oppGold = data[pvpOppKey() + 'Gold'] || 0;
  const oppName = data[pvpOppKey() + 'Name'] || 'your opponent';

  battleBody.innerHTML = '';
  battleModeTag.textContent = '';
  if (iWon) {
    const bonus = Math.floor(oppGold * PVP_GOLD_BONUS_PCT);
    session.record.coins = (session.record.coins || 0) + bonus;
    session.record.pvpWins = (session.record.pvpWins || 0) + 1;
    if (typeof myFinalHp === 'number') playerStats.hp = myFinalHp;
    saveSession();
    paintHud();
    battleBody.appendChild(statusHeading('Victory!'));
    const msg = document.createElement('div');
    msg.className = 'wb-modal-body';
    msg.textContent = `You defeated ${oppName}!` + (bonus > 0 ? ` +${bonus} \uD83E\uDE99 (10% of their gold).` : '');
    battleBody.appendChild(msg);
    battleBody.appendChild(gateButton('Nice!', () => { closeBattle(); pvpCode = null; }));
  } else {
    playerStats.hp = 1;
    saveSession();
    paintHud();
    battleBody.appendChild(statusHeading('Defeated!'));
    const msg = document.createElement('div');
    msg.className = 'wb-modal-body';
    msg.textContent = `${oppName} got the better of you this time. You wake up back home with 1 HP.`;
    battleBody.appendChild(msg);
    battleBody.appendChild(gateButton('Okay', () => {
      closeBattle();
      pvpCode = null;
      teleportToBedKnockedOut();
    }));
  }
}

function pvpEndAborted() {
  if (pvpEnded) return;
  pvpEnded = true;
  pvpClearTimers();
  pvpStopWatching();
  currentBattleFinish = null;
  battleBody.innerHTML = '';
  battleModeTag.textContent = '';
  battleBody.appendChild(statusHeading('Battle ended'));
  const msg = document.createElement('div');
  msg.className = 'wb-modal-body';
  msg.textContent = 'The connection to this battle was lost.';
  battleBody.appendChild(msg);
  battleBody.appendChild(gateButton('Okay', () => { closeBattle(); pvpCode = null; }));
}
